/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    RecurringBuy: {
      address: "0x065FD5E0e1E20E3Bd523aFba3994073edfc95911",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_router",
              type: "address",
            },
            {
              internalType: "address",
              name: "_whbar",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "CadenceTooShort",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "fundedTinybar",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "buyAmountTinybar",
              type: "uint256",
            },
          ],
          name: "InsufficientFunds",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidRouter",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidToken",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotStreamOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
          ],
          name: "NothingToWithdraw",
          type: "error",
        },
        {
          inputs: [],
          name: "SlippageTooHigh",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
          ],
          name: "StreamIsPaused",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "nextExecutionAt",
              type: "uint256",
            },
          ],
          name: "StreamNotDue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
          ],
          name: "StreamNotFound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "reason",
              type: "bytes",
            },
          ],
          name: "SwapFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "TokenAssociationFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "TokenTransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroBuyAmount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "sequence",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "buyAmountTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountOut",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
          ],
          name: "CadenceExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refundedTinybar",
              type: "uint256",
            },
          ],
          name: "StreamClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "buyAmountTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "cadenceSeconds",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxSlippageBps",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "maxCadences",
              type: "uint256",
            },
          ],
          name: "StreamCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
          ],
          name: "StreamPaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
          ],
          name: "StreamResumed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TokensWithdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_DEADLINE_LOOKAHEAD_SECONDS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_SLIPPAGE_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_CADENCE_SECONDS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_tokenOut",
              type: "address",
            },
          ],
          name: "accruedOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
          ],
          name: "closeStream",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_tokenOut",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_buyAmountTinybar",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_cadenceSeconds",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_maxSlippageBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_maxCadences",
              type: "uint256",
            },
          ],
          name: "createStream",
          outputs: [
            {
              internalType: "uint256",
              name: "streamId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
          ],
          name: "executeById",
          outputs: [
            {
              internalType: "uint256",
              name: "amountOut",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
          ],
          name: "getStream",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "tokenOut",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "buyAmountTinybar",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "cadenceSeconds",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxSlippageBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxCadences",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "executedCadences",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lastExecutionAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "nextExecutionAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "fundedTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPaused",
                  type: "bool",
                },
              ],
              internalType: "struct RecurringBuy.Stream",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
          ],
          name: "pauseStream",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
          ],
          name: "resumeStream",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "router",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "streamCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "streams",
          outputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOut",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "buyAmountTinybar",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "cadenceSeconds",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxSlippageBps",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "maxCadences",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executedCadences",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastExecutionAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "nextExecutionAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "fundedTinybar",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPaused",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
          ],
          name: "topUpStream",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "whbar",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_streamId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_tokenOut",
              type: "address",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40812867,
      hederaContractId: "0.0.10653896",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
